repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^README\.md$
      - id: trailing-whitespace
        exclude: ^README\.md$
      - id: check-yaml

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
    - id: terraform_fmt
      exclude: ^bootstrap/
    - id: terraform_validate
      exclude: ^bootstrap/
    - id: terraform_tflint
      exclude: ^bootstrap/
    - id: terraform_docs
      files: (\.tf|\.tfvars|\.hcl|Terraform/README\.md)$
      exclude: ^(bootstrap/|^README\.md)$
    - id: terraform_trivy
      exclude: ^bootstrap/
